services:
  redis:
    container_name: redis-stack
    #image: redis/redis-stack:latest # To download the latest image - You should avoid to download latest to have a better control on the version you use
    image: redis/redis-stack:7.4.0-v5 #  To download a specific version, here the version 7.4.0-v5
    ports:
      - 6379:6379 # HOST_PORT:CONTAINER_PORT
      - 8001:8001 # HOST_PORT:CONTAINER_PORT