services:
  postgres:
    # see https://hub.docker.com/_/postgres for list of postgres image versions on docker hub
    #image: postgres:latest # To download the latest image
    #image: postgres:17.4-alpine # To download a specific version, here the version 17.4 of Postgresql under an alpine linux distribution
    image: postgres:17.4 # To download a specific version, here the version 17.4 of Postgresql
    container_name: postgres
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    env_file:
      - .env    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # HOST_PORT:CONTAINER_PORT
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - postgres_network
  
  dtrack-apiserver:
    image: dependencytrack/apiserver:latest
    #image: dependencytrack/apiserver:snapshot
    container_name: dtrack-apiserver
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # The Dependency-Track container can be configured using any of the
      # available configuration properties defined in:
      # https://docs.dependencytrack.org/getting-started/configuration/
      # All properties are upper case with periods replaced by underscores.
      #
      # Database Properties
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=${POSTGRES_USER}
      - ALPINE_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - ALPINE_DATABASE_POOL_ENABLED=true
      - ALPINE_DATABASE_POOL_MAX_SIZE=20
      - ALPINE_DATABASE_POOL_MIN_IDLE=10
      - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=300000
      - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000
      - ALPINE_CORS_ENABLED=true
      - ALPINE_CORS_ALLOW_ORIGIN=*
      - ALPINE_CORS_ALLOW_METHODS=GET, POST, PUT, DELETE, OPTIONS
      - ALPINE_CORS_ALLOW_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count, *
      - ALPINE_CORS_EXPOSE_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count
      - ALPINE_CORS_ALLOW_CREDENTIALS=true
      - ALPINE_CORS_MAX_AGE=3600
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - '8081:8080'
    volumes:
      - 'dependency_track:/data'
    healthcheck:
      test: [ "CMD-SHELL", "wget -t 1 -T 3 --no-proxy -q -O /dev/null http://127.0.0.1:8080$${CONTEXT}health || exit 1" ]
      interval: 30s
      start_period: 60s
      timeout: 3s
    restart: unless-stopped
    networks:
      - postgres_network

  dtrack-frontend:
    image: dependencytrack/frontend:latest
    container_name: dtrack-frontend
    depends_on:
      dtrack-apiserver:
        condition: service_healthy
    environment:
      # The base URL of the API server.
      - API_BASE_URL=http://localhost:8081
    ports:
      - "8080:8080" # HOST_PORT:CONTAINER_PORT
    restart: unless-stopped
    networks:
      - postgres_network

  trivy-server:
    image: aquasec/trivy:latest
    container_name: trivy-server
    volumes:
      - 'trivy_cache_data:/root/.cache/'
    entrypoint: trivy server --listen 0.0.0.0:9000 --token ${TRIVY_SERVER_TOKEN}
    depends_on:
      - dtrack-apiserver
    ports:
      - "9000:9000" # HOST_PORT:CONTAINER_PORT
    restart: unless-stopped
    networks:
      - postgres_network

volumes:
  postgresql_data:
    driver: local
  dependency_track:
    driver: local
  trivy_cache_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
